name: textile_erp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^8.0.2
  supabase_flutter: ^2.4.0
  intl: ^0.20.2
  window_manager: ^0.5.1
  screen_retriever: ^0.2.0
  lucide_icons_flutter: ^3.1.14+2
  shadcn_flutter: ^0.0.53
  pluto_grid: ^8.0.0
  desktop_drop: ^0.7.0
  file_picker: ^11.0.2
  photo_view: ^0.15.0
  carousel_slider: ^5.0.0
  fl_chart: ^1.2.0
  image: ^4.8.0
  webview_windows: ^0.2.2
  super_clipboard: ^0.8.4
  url_launcher: ^6.3.2
  http: ^1.2.1
  meta: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  msix: ^3.16.1

msix_config:
  display_name: Ambaji Sarees ERP
  publisher_display_name: Ambaji Sarees
  publisher: CN=AmbajiSarees, O=AmbajiSarees, L=Surat, S=Gujarat, C=IN
  identity_name: com.ambajisaree.erp
  msix_version: 1.0.0.0
  logo_path: assets/icons/app_icon_source.png
  capabilities: internetClient, location, privateNetworkClientServer

flutter:
  uses-material-design: true


